function [interp_grid, interp_method, roundstart, roundend, roundstep] = ...
    gridchoice(npts,xstart,xend,dx,xunits, process)
%
%
global h_rb;

% Set some return arguments that might not otherwise be set.
roundstart = 0;
roundend = 0;
roundstep = 0;
h_f3 = figure('visible','on');
%  Create a QUIT button to allow the program to end early:
%q3 = uicontrol(h_f3,'units','normalized','style','pushbutton',...
%    'string','QUIT','fontsize',12, ...
%    'position',[0.88 0.92  0.1 0.05], ...
%    'callback',{@call_quit});
%set (q3,'UserData',0);

%  Print spacings
uicontrol('units','normalized','style','text','string',...
    'GRID TYPE                  # points         Start        End      Avg Spacing',...
    'position',[0.00 0.90 0.80 0.05], 'fontsize',10);
uicontrol('units','normalized',...
    'style','text','string','Experimental data:', ...
    'position',[0.0 0.85 0.25 0.05], 'fontsize',10);
uicontrol('units','normalized',...
    'style','text','string','Computational data:', ...
    'position',[0.0 0.80 0.25 0.05], 'fontsize',10);
uicontrol('units','normalized',...
    'style','text','string', 'Round number spacing:', ...
    'position',[0.01 0.75 0.26 0.05], 'fontsize',10);
uicontrol('units','normalized','style','text','string',...
    num2str(npts(1)),'position',[0.28 0.85 0.10 0.05],...
    'fontsize',10);
uicontrol('units','normalized','style','text','string',...
    num2str(npts(2)),'position',[0.28 0.80 0.10 0.05],...
    'fontsize',10);
uicontrol('units','normalized','style','text','string',...
    num2str(npts(3)),'position',[0.28 0.75 0.10 0.05],...
    'fontsize',10);
uicontrol('units','normalized','style','text','string',...
    num2str(xstart(1),4), 'position',[0.40 0.85 0.125 0.05],...
    'fontsize',10);
uicontrol('units','normalized','style','text','string',...
    num2str(xstart(2),4), 'position',[0.40 0.80 0.125 0.05],...
    'fontsize',10);
uicontrol('units','normalized','style','text','string',...
    num2str(xstart(3)),'position',[0.40 0.75 0.125 0.05],...
    'fontsize',10);
uicontrol('units','normalized','style','text','string',...
    num2str(xend(1),4), 'position',[0.525 0.85 0.125 0.05],...
    'fontsize',10);
uicontrol('units','normalized','style','text','string',...
    num2str(xend(2),4),'position',[0.525 0.80 0.125 0.05],...
    'fontsize',10);
uicontrol('units','normalized','style','text','string',...
    num2str(xend(3),4),'position',[0.525 0.75 0.125 0.05],...
    'fontsize',10);
uicontrol('units','normalized','style','text','string',...
    num2str(dx(1),4), 'position',[0.65 0.85 0.125 0.05],...
    'fontsize',10);
uicontrol('units','normalized','style','text','string',...
    num2str(dx(2),4),'position',[0.65 0.80 0.125 0.05],...
    'fontsize',10);
uicontrol('units','normalized','style','text','string',...
    num2str(dx(3)),  'position',[0.65 0.75 0.125 0.05],...
    'fontsize',10);
uicontrol('units','normalized','style','text','string',xunits, ...
    'position',[0.775 0.85 0.15 0.05], 'fontsize', 10);
uicontrol('units','normalized','style','text','string',xunits, ...
    'position',[0.775 0.80 0.15 0.05], 'fontsize', 10);
uicontrol('units','normalized','style','text','string',xunits, ...
    'position',[0.775 0.75 0.15 0.05], 'fontsize', 10);

done = 0;
if strcmp(process,'interpolation')
   h_rb = zeros(3,1);
   %done = get(q3,'UserData');
   interp_grid = ' ';
%  Ask which spacing to use for the validation calculations
% Don't end the grid-type request until a choice has been 
% made or until the QUIT button is selected.
   while ((interp_grid == ' ') & (done == 0)) 
      tx26 = uicontrol(h_f3,'units','normalized',...
        'style','text','string',...
        'Which interpolation grid do you want to use?',...
        'position',[0.0 0.65 0.50 0.05], 'fontsize',10);

      h_rb(1) = uicontrol(h_f3,'units','normalized',...
        'style','radiobutton','string','Experimental',...
        'position',[0.05 0.60  0.20 0.05], 'fontsize',10, ...
        'callback', {@callback_grid,'expgrid     '});
      h_rb(2) = uicontrol(h_f3,'units','normalized',...
        'style','radiobutton','string','Computational',...
        'position',[0.30 0.60 0.20 0.05], 'fontsize',10, ...
        'callback', {@callback_grid,'compgrid    '});
      h_rb(3) = uicontrol(h_f3,'units','normalized',...
        'style','radiobutton','string','Round number',...
        'position',[0.55 0.60  0.20 0.05], 'fontsize',10, ...
        'callback', {@callback_grid,'roundnumbers'});

% Wait for an answer about the grid-type choice
      uiwait;
   
      if get(h_rb(1),'value')
         interp_grid = 'experimental';
      elseif get(h_rb(2),'value')
         interp_grid = 'computational';
      elseif get(h_rb(3),'value')
         interp_grid = 'roundnumbers';
% Allow changes in the step, start, and end points:
         xmin = min(xstart);
         xmax = max(xend);
         [roundstep roundstart roundend nrpts] = ...
                                updatechoice(xmin,xmax,dx(3));
      end
          
% Was the QUIT button selected?
%   if get(q3,'UserData')
%      exit
%   end
   end
else
   tx2 = uicontrol(h_f3,'units','normalized',...
        'style','text','string',...
        'The regression option requires the use of the round number grid.',...
        'position',[0.0 0.65 0.80 0.05], 'fontsize',10);
   interp_grid = 'roundnumbers';
% Allow changes in the step, start, and end points:
         xmin = min(xstart);
         xmax = max(xend);
         [roundstep roundstart roundend nrpts] = ...
                                updatechoice(xmin,xmax,dx(3));
end
%  Ask what type of interpolation method to use:
interp_method = ' ';
%  Ask which spacing to use for the validation calculations
% Don't end the grid-type request until a choice has been 
% made or until the QUIT button is selected.
h_rb = zeros(2,1);
while ((interp_method == ' ') & (done == 0)) 
  tx1 = uicontrol(h_f3,'units','normalized',...
    'style','text','string',...
    'What interpolation method do you want to use?',...
    'position',[0.0 0.15 0.65 0.05], 'fontsize',10);

  h_rb(1) = uicontrol(h_f3,'units','normalized',...
    'style','radiobutton','string','linear',...
    'position',[0.05 0.10  0.20 0.05], 'fontsize',10, ...
    'callback', {@call_int_method,'linear'});
  h_rb(2) = uicontrol(h_f3,'units','normalized',...
    'style','radiobutton','string','spline',...
    'position',[0.30 0.10 0.20 0.05], 'fontsize',10, ...
    'callback', {@call_int_method,'spline'});
% Wait for an answer about the interpolation method
   uiwait;

   if get(h_rb(1),'value') 
       interp_method = 'linear';
   elseif get(h_rb(2),'value')
       interp_method = 'spline';
   end

% Was the QUIT button selected?
%   if get(q3,'UserData')
%      exit
%   end
end
close(h_f3);
%  end gridchoice